name = "TernaryFrames"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TernaryFrames"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "TernaryFrames"
